### ISSUE TITLE
Crash on Android 6.0.1 Posthog "Could not create instance of com.posthog.android.Properties"

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#1104]
AssertionError

```
java.lang.AssertionError: Could not create instance of com.posthog.android.Properties.
java.lang.NoSuchMethodException: <init> [interface java.util.Map]
    at com.posthog.android.payloads.ScreenPayload.toString(SourceFile:93)
    at java.lang.StringBuilder.append(StringBuilder.java:202)
    at android.os.Message.toString(Message.java:515)
    at android.os.Message.toString(Message.java:486)
    at android.os.BaseLooper.getMessageString(BaseLooper.java:342)
    at android.os.BaseLooper$MessageMonitorInfo.setMonitorMessage(BaseLooper.java:287)
    at android.os.BaseLooper.updateMessageByState(BaseLooper.java:55)
    at android.os.Looper.loop(Looper.java:152)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

https://sentry.tools.element.io/organizations/element/issues/84413

**Comment by jmartinesp** [comment]
Some context on this:

It's crashing [here](https://github.com/PostHog/posthog-android/blob/master/posthog/src/main/java/com/posthog/android/ValueMap.java#L72).

`Properties` does have [that constructor](https://github.com/PostHog/posthog-android/blob/master/posthog/src/main/java/com/posthog/android/Properties.java#L71).

I don't get why it would look for the default constructor of `Map` using reflection though.

**Comment by bmarty** [comment]
I do not get it too...

To fix the issue, there is maybe a missing Proguard rule?

This is an extract of the proguard usage file I have built locally:

```
com.posthog.android.Properties:
    private static final java.lang.String ACTIVE_FEATURE_FLAGS_KEY
    private static final java.lang.String ANONYMOUS_ID_KEY
    private static final java.lang.String DISTINCT_ID_KEY
    private static final java.lang.String FEATURE_FLAG_KEY_PREFIX
    private static final java.lang.String GROUPS_KEY
    public void <init>(int)
    public java.util.ArrayList activeFeatureFlags(java.lang.String)
    public java.lang.String currentId()
    public java.lang.String featureFlag(java.lang.String)
    com.posthog.android.Properties putDistinctId(java.lang.String)
    com.posthog.android.Properties putGroups(com.posthog.android.ValueMap)
    public synthetic bridge com.posthog.android.ValueMap putValue(java.lang.String,java.lang.Object)
    public com.posthog.android.Properties unmodifiableCopy()
```

So it looks like the constructor has been stripped out IIUC.

But I am wondering why the app is not crashing more.

**Comment by bmarty** [comment]
I think we can just disable PostHog for Android 6 to get ride of this crash.

**Comment by jmartinesp** [comment]
The library can't crash if there's no library 👌 . Jokes aside, I don't see any other solution either. How was this not crashing on EA?

**Comment by bmarty** [comment]
Giving a try to the kotlin version of the lib https://github.com/PostHog/posthog-android/releases/tag/3.0.0-RC.1
