### ISSUE TITLE
Some configuration change crashes the app

### ISSUE THREAD

**Issue by julioromano** [vector-im/element-x-android#413]
### Steps to reproduce

1. Open app
2. Trigger a configuration changes which is not among the ignored ones in the manifest: `android:configChanges="orientation|screenSize|screenLayout|keyboardHidden|uiMode"` For instance go to "Wallpaper & Style" and change the wallpaper colors.
3. Reopen the app.
4. App crashes with:

```
Thread: main, Exception: java.lang.RuntimeException: Unable to resume activity {io.element.android.x.debug/io.element.android.x.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property mainNode has not been initialized
                                                                                                    	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4773)
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4806)
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: kotlin.UninitializedPropertyAccessException: lateinit property mainNode has not been initialized
                                                                                                    	at io.element.android.x.MainActivity.getMainNode(MainActivity.kt:42)
                                                                                                    	at io.element.android.x.MainActivity.onNewIntent(MainActivity.kt:87)
                                                                                                    	at android.app.Activity.performNewIntent(Activity.java:8321)
                                                                                                    	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1517)
                                                                                                    	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1530)
                                                                                                    	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3822)
                                                                                                    	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4756)
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4806) 
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54) 
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

I'm not sure this is actually due to the configuration change. The issue seems more about `onNewIntent()` (which I guess is called because we are opening a singleInstance existing activity by clicking on its launcher icon) is racing with `onCreate()` for accessing `var lateinit mainNode` .

This opens another question? Why MainActivity has `android:launchMode="singleInstance"` ? Removing it actually fixes the issue, but I was wondering what is the particular reason that forces us to use `singleInstance`. 

#### What did you expect?
App crashed

#### What happened instead?
App did not crash

### Your phone model

Pixel 6a or Emulator

### Operating system version

Android 13

### Application version and app store

EAX latest from develop

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
Thanks for creating the issue. I think @ganfra wanted to rework this part.

Also I observe the same issue on Android 13 by following this steps:
- start the app
- go to the system settings and disable permission to display notification
- resume the app.

**Comment by julioromano** [comment]
Yepp another way to reproduce (on Android 13) is to just open the App and then put it to background and leave the phone unattended for one hour or so...
Next time you open the app it will crash like this.
